name: 部署 MkDocs 文档

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 获取仓库内容
        uses: actions/checkout@v4

      - name: 配置 Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: 安装 MkDocs Material
        run: pip install mkdocs-material

      - name: 部署文档
        run: mkdocs gh-deploy --force